version: "3.8"
services:
  mysql:
    image: mysql:8.0.21
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'sff'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'syscorer'
      # You can use whatever password you like
      MYSQL_PASSWORD: 's6s@#@!L0ngh'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root123'
    ports:
      # Opens port 3306 on the container
      - "3306:3306"
    # Where our data will be persisted
    volumes:
      - "./data:/var/lib/mysql"
      - "./conf/my.cnf:/etc/my.cnf"